# TCL File Generated by Component Editor 15.0
# Fri Feb 26 22:46:24 PST 2016
# DO NOT MODIFY


# 
# i2c_AVALON "i2c_AVALON" v1.0
# Cory Barney 2016.02.26.22:46:24
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module i2c_AVALON
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_AVALON
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom
set_module_property AUTHOR "Cory Barney"
set_module_property DISPLAY_NAME i2c_AVALON
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL I2C_AVALON
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file I2C_AVALON.v VERILOG PATH I2C_AVALON.v TOP_LEVEL_FILE
add_fileset_file i2cModule.v VERILOG PATH i2cModule.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL I2C_AVALON
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file I2C_AVALON.v VERILOG PATH I2C_AVALON.v
add_fileset_file i2cModule.v VERILOG PATH i2cModule.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point i2c
# 
add_interface i2c avalon end
set_interface_property i2c addressUnits WORDS
set_interface_property i2c associatedClock clock
set_interface_property i2c associatedReset reset
set_interface_property i2c bitsPerSymbol 8
set_interface_property i2c burstOnBurstBoundariesOnly false
set_interface_property i2c burstcountUnits WORDS
set_interface_property i2c explicitAddressSpan 0
set_interface_property i2c holdTime 0
set_interface_property i2c linewrapBursts false
set_interface_property i2c maximumPendingReadTransactions 0
set_interface_property i2c maximumPendingWriteTransactions 0
set_interface_property i2c readLatency 0
set_interface_property i2c readWaitTime 1
set_interface_property i2c setupTime 0
set_interface_property i2c timingUnits Cycles
set_interface_property i2c writeWaitTime 0
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c CMSIS_SVD_VARIABLES ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c i2c_chipselect chipselect Input 1
add_interface_port i2c i2c_write write Input 1
add_interface_port i2c i2c_address address Input 2
add_interface_port i2c i2c_writedata writedata Input 32
add_interface_port i2c i2c_readdata readdata Output 32
set_interface_assignment i2c embeddedsw.configuration.isFlash 0
set_interface_assignment i2c embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment i2c embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment i2c embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end i2c_reset rst Output 1
add_interface_port conduit_end i2c_sda sda Bidir 1
add_interface_port conduit_end i2c_sclk sclk Bidir 1

