# TCL File Generated by Component Editor 15.0
# Sat Apr 02 23:29:30 PDT 2016
# DO NOT MODIFY


# 
# LCDFrameBuffer "LCDFrameBuffer" v1.0
# Cory Barney 2016.04.02.23:29:30
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module LCDFrameBuffer
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCDFrameBuffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom
set_module_property AUTHOR "Cory Barney"
set_module_property DISPLAY_NAME LCDFrameBuffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_AVALON
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCDController.sv SYSTEM_VERILOG PATH LCDController.sv
add_fileset_file LCD_AVALON.sv SYSTEM_VERILOG PATH LCD_AVALON.sv TOP_LEVEL_FILE
add_fileset_file framebuffer_arbiter.v VERILOG PATH framebuffer_arbiter.v
add_fileset_file sdram_read_fifo.v VERILOG PATH sdram_read_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL LCD_AVALON
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCDController.sv SYSTEM_VERILOG PATH LCDController.sv
add_fileset_file LCD_AVALON.sv SYSTEM_VERILOG PATH LCD_AVALON.sv
add_fileset_file framebuffer_arbiter.v VERILOG PATH framebuffer_arbiter.v
add_fileset_file sdram_read_fifo.v VERILOG PATH sdram_read_fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset rst
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 s0_address address Input 2
add_interface_port s0 s0_read read Input 1
add_interface_port s0 s0_write write Input 1
add_interface_port s0 s0_chipselect chipselect Input 1
add_interface_port s0 s0_writedata writedata Input 32
add_interface_port s0 s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point External
# 
add_interface External conduit end
set_interface_property External associatedClock ""
set_interface_property External associatedReset ""
set_interface_property External ENABLED true
set_interface_property External EXPORT_OF ""
set_interface_property External PORT_NAME_MAP ""
set_interface_property External CMSIS_SVD_VARIABLES ""
set_interface_property External SVD_ADDRESS_GROUP ""

add_interface_port External lcd_cs lcd_cs Output 1
add_interface_port External lcd_data lcd_data Output 24
add_interface_port External lcd_dc lcd_dc Output 1
add_interface_port External lcd_rst lcd_rst Output 1
add_interface_port External lcd_wr lcd_wr Output 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clock
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset rst
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 2
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master m0_waitrequest waitrequest Input 1
add_interface_port avalon_master m0_readdatavalid readdatavalid Input 1
add_interface_port avalon_master m0_readdata readdata Input 16
add_interface_port avalon_master m0_address address Output 26
add_interface_port avalon_master m0_writedata writedata Output 16
add_interface_port avalon_master m0_chipselect chipselect Output 1
add_interface_port avalon_master m0_byteenable_n byteenable_n Output 2
add_interface_port avalon_master m0_read_n read_n Output 1
add_interface_port avalon_master m0_write_n write_n Output 1

