# TCL File Generated by Component Editor 15.0
# Sun Feb 14 01:13:33 PST 2016
# DO NOT MODIFY


# 
# SPI_AVALON_SD "SPI_AVALON_SD" v1.0
#  2016.02.14.01:13:33
# SPI controller for sd card. Allows dynamic clock speeds.
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module SPI_AVALON_SD
# 
set_module_property DESCRIPTION "SPI controller for sd card. Allows dynamic clock speeds."
set_module_property NAME SPI_AVALON_SD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SPI_AVALON_SD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SPI_AVALON_SD
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SPI_AVALON_SD.v VERILOG PATH SPI_AVALON_SD.v TOP_LEVEL_FILE
add_fileset_file SPI_CONTROLLER.v VERILOG PATH SPI_CONTROLLER.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point sd
# 
add_interface sd avalon end
set_interface_property sd addressUnits WORDS
set_interface_property sd associatedClock clock
set_interface_property sd associatedReset reset
set_interface_property sd bitsPerSymbol 8
set_interface_property sd burstOnBurstBoundariesOnly false
set_interface_property sd burstcountUnits WORDS
set_interface_property sd explicitAddressSpan 0
set_interface_property sd holdTime 0
set_interface_property sd linewrapBursts false
set_interface_property sd maximumPendingReadTransactions 0
set_interface_property sd maximumPendingWriteTransactions 0
set_interface_property sd readLatency 0
set_interface_property sd readWaitTime 1
set_interface_property sd setupTime 0
set_interface_property sd timingUnits Cycles
set_interface_property sd writeWaitTime 0
set_interface_property sd ENABLED true
set_interface_property sd EXPORT_OF ""
set_interface_property sd PORT_NAME_MAP ""
set_interface_property sd CMSIS_SVD_VARIABLES ""
set_interface_property sd SVD_ADDRESS_GROUP ""

add_interface_port sd sd_chipselect chipselect Input 1
add_interface_port sd sd_write write Input 1
add_interface_port sd sd_address address Input 2
add_interface_port sd sd_writedata writedata Input 32
add_interface_port sd sd_readdata readdata Output 32
set_interface_assignment sd embeddedsw.configuration.isFlash 0
set_interface_assignment sd embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment sd embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment sd embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end sd_cs sd_cs Output 1
add_interface_port conduit_end sd_clk sd_clk Output 1
add_interface_port conduit_end sd_di sd_di Output 1
add_interface_port conduit_end sd_do sd_do Input 1

