/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'DE1_SOC_NIOS_2'
 * SOPC Builder design path: ../../DE1_SOC_NIOS_2.sopcinfo
 *
 * Generated: Wed Apr 20 18:43:11 PDT 2016
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x04080820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1b
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x04040020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1b
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x04040000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x04080820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1b
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x04040020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1b
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x04040000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __I2C_AVALON
#define __LCDFRAMEBUFFER
#define __SPI_AVALON_SD


/*
 * LCDFrameBuffer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_LCDFrameBuffer_0 LCDFrameBuffer
#define LCDFRAMEBUFFER_0_BASE 0x4081060
#define LCDFRAMEBUFFER_0_IRQ -1
#define LCDFRAMEBUFFER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCDFRAMEBUFFER_0_NAME "/dev/LCDFrameBuffer_0"
#define LCDFRAMEBUFFER_0_SPAN 16
#define LCDFRAMEBUFFER_0_TYPE "LCDFrameBuffer"


/*
 * SPI_AVALON_SD_0 configuration
 *
 */

#define ALT_MODULE_CLASS_SPI_AVALON_SD_0 SPI_AVALON_SD
#define SPI_AVALON_SD_0_BASE 0x4081050
#define SPI_AVALON_SD_0_IRQ -1
#define SPI_AVALON_SD_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPI_AVALON_SD_0_NAME "/dev/SPI_AVALON_SD_0"
#define SPI_AVALON_SD_0_SPAN 16
#define SPI_AVALON_SD_0_TYPE "SPI_AVALON_SD"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x4081070
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x4081070
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x4081070
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "DE1_SOC_NIOS_2"


/*
 * dma_0 configuration
 *
 */

#define ALT_MODULE_CLASS_dma_0 altera_avalon_dma
#define DMA_0_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_0_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_HW_TRANSACTIONS 1
#define DMA_0_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_WORD_TRANSACTIONS 0
#define DMA_0_BASE 0x4081020
#define DMA_0_IRQ 2
#define DMA_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_0_LENGTHWIDTH 20
#define DMA_0_MAX_BURST_SIZE 128
#define DMA_0_NAME "/dev/dma_0"
#define DMA_0_SPAN 32
#define DMA_0_TYPE "altera_avalon_dma"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * i2c_AVALON_0 configuration
 *
 */

#define ALT_MODULE_CLASS_i2c_AVALON_0 i2c_AVALON
#define I2C_AVALON_0_BASE 0x4081040
#define I2C_AVALON_0_IRQ 3
#define I2C_AVALON_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define I2C_AVALON_0_NAME "/dev/i2c_AVALON_0"
#define I2C_AVALON_0_SPAN 16
#define I2C_AVALON_0_TYPE "i2c_AVALON"


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x4081070
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * new_sdram_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_new_sdram_controller_0 altera_avalon_new_sdram_controller
#define NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define NEW_SDRAM_CONTROLLER_0_IRQ -1
#define NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 100.0
#define NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define NEW_SDRAM_CONTROLLER_0_SPAN 67108864
#define NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define NEW_SDRAM_CONTROLLER_0_T_AC 5.4
#define NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define NEW_SDRAM_CONTROLLER_0_T_RCD 15.0
#define NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define NEW_SDRAM_CONTROLLER_0_T_RP 15.0
#define NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * new_sdram_controller_0 configuration as viewed by dma_0_read_master
 *
 */

#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ -1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 100.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_SPAN 67108864
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_AC 5.4
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RCD 15.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_RP 15.0
#define DMA_0_READ_MASTER_NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * new_sdram_controller_0 configuration as viewed by dma_0_write_master
 *
 */

#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_BASE 0x0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ -1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_NAME "/dev/new_sdram_controller_0"
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_POWERUP_DELAY 100.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_SPAN 67108864
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_AC 5.4
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_MRD 3
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RCD 15.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RFC 70.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_RP 15.0
#define DMA_0_WRITE_MASTER_NEW_SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * onchip_memory2 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_BASE 0x4040000
#define ONCHIP_MEMORY2_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_DUAL_PORT 0
#define ONCHIP_MEMORY2_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_INIT_CONTENTS_FILE "DE1_SOC_NIOS_2_onchip_memory2"
#define ONCHIP_MEMORY2_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_IRQ -1
#define ONCHIP_MEMORY2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_NAME "/dev/onchip_memory2"
#define ONCHIP_MEMORY2_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_SIZE_VALUE 204800
#define ONCHIP_MEMORY2_SPAN 204800
#define ONCHIP_MEMORY2_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_WRITABLE 1


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x4081000
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_IRQ 1
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 24999999
#define TIMER_0_MULT 0.001
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 500
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 2
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
